#!/bin/bash

# Copyright 2019 The Kubernetes Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

mockgen -package=cloud -destination=./pkg/cloud/mock_efs.go -source pkg/cloud/efs_interface.go
mockgen -package=cloud -destination=./pkg/cloud/mock_cloud.go -source pkg/cloud/cloud_interface.go
mockgen -package=cloud -destination=./pkg/cloud/mock_metadata.go -source pkg/cloud/metadata_interface.go
mockgen -package=driver -destination=./pkg/driver/mock_mounter.go -source pkg/driver/mounter.go
