{{- if .Values.controller.httpProxy }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: efs-csi-controller-proxy
data:
  httpProxy: "{{ .Values.controller.httpProxy | b64enc }}"
  httpsProxy: "{{ .Values.controller.httpsProxy | default .Values.controller.httpProxy | b64enc }}"
  noProxy: "{{ printf "%s,.%s.svc,.%s.svc.cluster.local" .Values.controller.noProxy .Release.Namespace .Release.Namespace | b64enc }}"
{{- end }}