// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/cloud (interfaces: S3Files)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	s3files "github.com/aws/aws-sdk-go-v2/service/s3files"
	gomock "github.com/golang/mock/gomock"
)

// MockS3Files is a mock of S3Files interface.
type MockS3Files struct {
	ctrl     *gomock.Controller
	recorder *MockS3FilesMockRecorder
}

// MockS3FilesMockRecorder is the mock recorder for MockS3Files.
type MockS3FilesMockRecorder struct {
	mock *MockS3Files
}

// NewMockS3Files creates a new mock instance.
func NewMockS3Files(ctrl *gomock.Controller) *MockS3Files {
	mock := &MockS3Files{ctrl: ctrl}
	mock.recorder = &MockS3FilesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Files) EXPECT() *MockS3FilesMockRecorder {
	return m.recorder
}

// CreateAccessPoint mocks base method.
func (m *MockS3Files) CreateAccessPoint(arg0 context.Context, arg1 *s3files.CreateAccessPointInput, arg2 ...func(*s3files.Options)) (*s3files.CreateAccessPointOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateAccessPoint", varargs...)
	ret0, _ := ret[0].(*s3files.CreateAccessPointOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessPoint indicates an expected call of CreateAccessPoint.
func (mr *MockS3FilesMockRecorder) CreateAccessPoint(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessPoint", reflect.TypeOf((*MockS3Files)(nil).CreateAccessPoint), varargs...)
}

// DeleteAccessPoint mocks base method.
func (m *MockS3Files) DeleteAccessPoint(arg0 context.Context, arg1 *s3files.DeleteAccessPointInput, arg2 ...func(*s3files.Options)) (*s3files.DeleteAccessPointOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAccessPoint", varargs...)
	ret0, _ := ret[0].(*s3files.DeleteAccessPointOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccessPoint indicates an expected call of DeleteAccessPoint.
func (mr *MockS3FilesMockRecorder) DeleteAccessPoint(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessPoint", reflect.TypeOf((*MockS3Files)(nil).DeleteAccessPoint), varargs...)
}

// ListAccessPoints mocks base method.
func (m *MockS3Files) ListAccessPoints(arg0 context.Context, arg1 *s3files.ListAccessPointsInput, arg2 ...func(*s3files.Options)) (*s3files.ListAccessPointsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAccessPoints", varargs...)
	ret0, _ := ret[0].(*s3files.ListAccessPointsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessPoints indicates an expected call of ListAccessPoints.
func (mr *MockS3FilesMockRecorder) ListAccessPoints(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessPoints", reflect.TypeOf((*MockS3Files)(nil).ListAccessPoints), varargs...)
}

// ListFileSystems mocks base method.
func (m *MockS3Files) ListFileSystems(arg0 context.Context, arg1 *s3files.ListFileSystemsInput, arg2 ...func(*s3files.Options)) (*s3files.ListFileSystemsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFileSystems", varargs...)
	ret0, _ := ret[0].(*s3files.ListFileSystemsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFileSystems indicates an expected call of ListFileSystems.
func (mr *MockS3FilesMockRecorder) ListFileSystems(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFileSystems", reflect.TypeOf((*MockS3Files)(nil).ListFileSystems), varargs...)
}
